//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "NF_HardwareLib.h"

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_NF_HardwareLib_NF_HardwareLib_ChipInformation::NativeGetFlashInfo___STATIC__VOID__SZARRAY_U1,
    NULL,
    Library_NF_HardwareLib_NF_HardwareLib_ChipInformation::NativeGetFeatures___STATIC__VOID__SZARRAY_U1,
    NULL,
    Library_NF_HardwareLib_NF_HardwareLib_ChipInformation::NativeGetRevisionNumber___STATIC__VOID__SZARRAY_U1,
    NULL,
    Library_NF_HardwareLib_NF_HardwareLib_ChipInformation::NativeGetChipId___STATIC__VOID__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_HardwareLib =
{
    "NF.HardwareLib",
    0x9B65071D,
    method_lookup,
    { 1, 0, 0, 0 }
};
