//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef _NF_HARDWARELIB_H_
#define _NF_HARDWARELIB_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>

struct Library_NF_HardwareLib_NF_HardwareLib_ChipInformation
{
    NANOCLR_NATIVE_DECLARE(NativeGetFlashInfo___STATIC__VOID__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeGetFeatures___STATIC__VOID__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeGetRevisionNumber___STATIC__VOID__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeGetChipId___STATIC__VOID__SZARRAY_U1);

    //--//

};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_HardwareLib;

#endif  //_NF_HARDWARELIB_H_
